### ISSUE TITLE
You stole my Task?

### ISSUE THREAD

**Issue by NickTehUnicorn** [QuiverlyRivalry/CRcore#2]
Really, you could have asked.
Anyway, to use it, you must call it somewhere in the Main.php
Like
`$this->getServer()->getScheduler()->scheduleDelayedTask(new Task($player));`

**Comment by winterbuild7074** [comment]
Don’t be rude, Nick, this is not a good reason to complain.

**Comment by NickTehUnicorn** [comment]
I'm not trying to be rude, nor complaining.
He copied the task from my plugin and didn't even use it! I just wanted to tell him the usage.

**Comment by QuiverlyRivalry** [comment]
lmao sorry nick u werent online in discord so i juat did it anyways but forgot to ask chu

**Comment by QuiverlyRivalry** [comment]
Oh and hi @winterbuild7074
